baseURL = "https://abbasov.dev"
languageCode = "en-us"
title = "Jeyhun Abbasov"
theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

# [[Menus.main]]
# identifier = "blog"
# name = "Blog"
# title = "Blog posts"
# url = "/blogs"
# weight = 1

[params]
title = ""
description = "Jeyhun's personal website"
favicon = "/fav.png"
useBootstrapCDN = false
mathjax = false
animate = true

  [params.theme]
  disableThemeToggle = true
  defaultTheme = "light"

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = ""
  disableSearch = true

    [params.navbar.stickyNavBar]
    enable = true
    showOnScrollUp = true

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableAchievements = false
    disableContact = false

  [params.hero]
  enable = true
  intro = "Hi, my name is"
  title = "Jeyhun."
  subtitle = "I build epic web apps"
  content = "A senior software engineer with over 8 years of experience, based in "
  image = "/images/main.png"
  logo = "/images/ee-flag.gif"

    [params.hero.bottomImage]
    enable = true

    [params.hero.button]
    enable = true
    download = false
    name = "Say hi"
    url = "mailto:jeyhun@abbasov.dev"
    image = "/images/giphy.gif"

    [[params.hero.socialLinks.fontAwesomeIcons]]
    enable = true
    icon = "fab fa-linkedin"
    url = "https://www.linkedin.com/in/abbasovdev/"

    [[params.hero.socialLinks.fontAwesomeIcons]]
    enable = true
    icon = "fab fa-github"
    url = "https://github.com/abbcyhn"

    [[params.hero.socialLinks.fontAwesomeIcons]]
    enable = true
    icon = "fab fa-x-twitter"
    url = "https://x.com/abbcyhn"



  [params.about]
  enable = true
  title = "About Me"
  image = "/images/about.png"
  content = """
I am a Senior Software Engineer with 8+ years of professional experience in the Finance and Government sectors, and a solid
6 year academic background in Computer Science. I speak English, Turkish, Azerbaijani, and a bit of Estonian."""

    [params.about.skills]
    enable = true
    title = "I've mostly worked with these tools/technologies during my career:"
    items = [ "Java", "Spring", "Spring Boot", "Hibernate", "JUnit", "Mockito", "Maven", "Gradle", "Git", "OOP", "REST", "SOAP", "WebSocket", "SQL", "Oracle SQL", "PL/SQL", "PostgreSQL", "MS Server", "IMB Db2", "Kafka", "RabbitMQ", "Redis", "Github Actions", "Bash", "Docker", "Kubernetes", "CI/CD", "HTML5", "CSS3", "Javascript", "Jquery", "Ajax", "JSON", "XML", "Bootstrap", "C#", "Python", "Cloud", "AWS", "AZURE", "Jenkins", "Logging", "Linux", "Monitoring", "Prometheus", "Grafana" ]

  [params.experience]
  enable = false

  [params.education]
  enable = false

  [params.achievements]
  enable = false

  [params.projects]
  enable = false

  [params.contact]
  enable = true
  content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
  btnName = "Mail me 📬"
  btnLink = "mailto:jeyhun@abbasov.dev"

[params.footer.copyright.logo]
enable = false

[params.footer.copyright.madewith]
enable = false

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
enable = false
github = "https://github.com"
linkedin = "https://linkedin.com"
twitter = "https://twitter.com"
instagram = "https://instagram.com"
facebook = "https://facebook.com"

  [params.listPages]
  disableFeaturedImage = false

[params.singlePages.readTime]
enable = true
content = "min read"

[params.singlePages.scrollprogress]
enable = true

  [params.terms]
  read = "Read"
  toc = "Table Of Contents"
  copyright = "All rights reserved"
  pageNotFound = "Page not found"
  emailText = "Check out this site"

  [params.datesFormat]
  article = "Jan 2, 2006"
  articleList = "Jan 2, 2006"
  articleRecent = "Jan 2, 2006"
