baseURL = "https://abbasov.dev"
languageCode = "en-us"
title = "Jeyhun Abbasov"
theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

# [[Menus.main]]
# identifier = "blog"
# name = "Blog"
# title = "Blog posts"
# url = "/blogs"
# weight = 1

[params]
title = ""
description = "Jeyhun's personal website"
favicon = "/fav.png"
useBootstrapCDN = false
mathjax = false
animate = true

  [params.theme]
  disableThemeToggle = true
  defaultTheme = "light"

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = ""
  disableSearch = true

    [params.navbar.stickyNavBar]
    enable = true
    showOnScrollUp = true

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableAchievements = false
    disableContact = false

  [params.hero]
  enable = true
  intro = "Hi, my name is"
  title = "Jeyhun."
  subtitle = "I build epic apps for the web"
  content = "A passionate web app developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
  image = "/images/main.png"

    [params.hero.bottomImage]
    enable = true

    [params.hero.button]
    enable = true
    download = false
    name = "Say hi 👋"
    url = "mailto:jeyhun@abbasov.dev"

    [[params.hero.socialLinks.fontAwesomeIcons]]
    enable = true
    icon = "fab fa-linkedin"
    url = "https://www.linkedin.com/in/abbasovdev/"

    [[params.hero.socialLinks.fontAwesomeIcons]]
    enable = true
    icon = "fab fa-github"
    url = "https://github.com/abbcyhn"

    [[params.hero.socialLinks.fontAwesomeIcons]]
    enable = true
    icon = "fab fa-x-twitter"
    url = "https://x.com/abbcyhn"



  [params.about]
  enable = true
  title = "About Me"
  image = "/images/about.png"
  content = """
I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. 

I am currently working on a project that will be used to help people find the best way to get around the city."""

    [params.about.skills]
    enable = true
    title = "Here are a few technologies I've been working with recently:"
    items = [ "HTML", "CSS", "JavaScript", "React", "Node", "Express", "HTML", "CSS", "JavaScript", "React", "Node", "Express", "HTML", "CSS", "JavaScript", "React", "Node", "Express", "HTML", "CSS", "JavaScript", "React", "Node", "Express" ]

  [params.experience]
  enable = false

  [params.education]
  enable = false

  [params.achievements]
  enable = false

  [params.projects]
  enable = false

  [params.contact]
  enable = true
  content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
  btnName = "Mail me 📬"
  btnLink = "mailto:jeyhun@abbasov.dev"

[params.footer.copyright.logo]
enable = false

[params.footer.copyright.madewith]
enable = false

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
enable = false
github = "https://github.com"
linkedin = "https://linkedin.com"
twitter = "https://twitter.com"
instagram = "https://instagram.com"
facebook = "https://facebook.com"

  [params.listPages]
  disableFeaturedImage = false

[params.singlePages.readTime]
enable = true
content = "min read"

[params.singlePages.scrollprogress]
enable = true

  [params.terms]
  read = "Read"
  toc = "Table Of Contents"
  copyright = "All rights reserved"
  pageNotFound = "Page not found"
  emailText = "Check out this site"

  [params.datesFormat]
  article = "Jan 2, 2006"
  articleList = "Jan 2, 2006"
  articleRecent = "Jan 2, 2006"
